-   id: post-code-summary
    name: generate code summary
    description: provides feedback
    entry: post-code-summary
    verbose: true
    language: python
    stages: [pre-commit, manual]
    minimum_pre_commit_version: 3.2.0
