repos:
  - repo: local
    hooks:
      - id: python-script
        name: Python Script
        entry: python scripts/my_script.py
        language: python
        types: [python]

      - id: bash-script
        name: Bash Script
        entry: bash scripts/my_script.sh
        language: system
        types: [bash]
